name: Cypress Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Prisma migrations
        run: npx prisma migrate deploy

      - name: Build Remix app
        run: npm run build

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          start: npm run start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
